#!/bin/bash
#
# Diff the output of a candidate program against a solution program.
#
# Usage: progdiff solution candidate [ -o 'options' ]
#   -o default string of options required by the solution and candidate programs to generate 
#       the required output

usage () {                                                       # print usage message & terminate
    echo "Usage: $(basename "$0") solution candidate [ -o 'options' ]" >&2
    exit 1
}

progdiff_run () {
    touch "${1}.in"

    $("${solution}" ${options} < "${1}.in" > "${1}.out")

    regress "${candidate}" -o "${options}" -p "${1}"

    exitstatus="${?}"

    # Clean up
    rm -f "${1}.in"
    rm -f "${1}.out"
}

if [ "${#}" -lt 2 ]; then
    usage
fi

solution="${1}"
shift

type "${solution}" &> /dev/null
if [ "${?}" -ne 0 ]; then                                       # solution program exists ?
   echo "program \"${solution}\" cannot be run" >&2	
   exit 1
fi

candidate="${1}"
shift

type "${candidate}" &> /dev/null
if [ "${?}" -ne 0 ]; then                                       # candidate program exists ?
   echo "program \"${candidate}\" cannot be run" >&2	
   exit 1
fi

options=""
while [ ${#} -gt 0 ]; do                                        # process command-line arguments
    case "${1}" in
    '-o') options="${2}"; shift ;;                              # options ?
    *)
    esac
    shift
done

progdiff_run "test-$RANDOM"                                     # generate random prefix for test

exit $exitstatus                                                # propogate exist status from regress  
