#!/bin/bash
#
# Diff the output of a candidate program against a solution program.
#
# Usage: progdiff solution candidate [ -o 'options' ] [ prefix-list ]
#   -o default string of options required by the solution and candidate programs to generate 
#       the required output

usage () {                                                       # print usage message & terminate
    echo "Usage: $(basename "$0") solution candidate [ -o 'options' ] [ prefix-list ]" >&2
    exit 1
}

progdiff_run () {
    if [ ! -r "${1}.in" ]; then                            # input file exists with read permission ?
        echo "cannot read input file ${1}.in" >&2 	
        exit 1
    fi

    $("${solution}" ${options} < "${1}.in" > "${1}.out")

    regress "${candidate}" -o "${options}" -p "${1}"

    exitstatus="${?}"

    rm -f "${1}.out"
}

if [ "${#}" -lt 2 ]; then
    usage
fi

solution="${1}"
shift

type "${solution}" &> /dev/null
if [ "${?}" -ne 0 ]; then                                       # solution program exists ?
   echo "program \"${solution}\" cannot be run" >&2	
   exit 1
fi

candidate="${1}"
shift

type "${candidate}" &> /dev/null
if [ "${?}" -ne 0 ]; then                                       # candidate program exists ?
   echo "program \"${candidate}\" cannot be run" >&2	
   exit 1
fi

options=""
while [ ${#} -gt 0 ]; do                                        # process command-line arguments
    case "${1}" in
    '-o') options="${2}"; shift ;;                              # options ?
    *)                                                          # prefix-list ?
        while [ ${#} -gt 0 ]; do
            progdiff_run ${1}
            shift
        done
        exit $exitstatus                                        # propogate exist status from regres
        ;;	
    esac
    shift
done

# For convenience, allow no prefixes to be specified by passing an empty temporary file 
# with a random name to regress.

prefix="test$RANDOM"                                            # generate random prefix for test       

if [ -f "${prefix}.in" ]; then
    rm -f "${prefix}.in"
fi
touch "${prefix}.in"                                            # hack: dummy input file for regress 

progdiff_run "${prefix}"

rm -f "${prefix}.in"                                            # cleanup dummy input file

exit $exitstatus                                                # propogate exist status from regress  
